language: go

go:
  - 1.7
  - 1.8
  - tip

matrix:
  allow_failures:
    - go: tip

before_install:
  - sudo apt-get update -y
  - sudo apt-get install -y make git doxygen
  - openssl aes-256-cbc -K $encrypted_c998de5db475_key -iv $encrypted_c998de5db475_iv -in travisci_rsa.enc -out travisci_rsa -d

script:
  - make
  - sudo make install
  - export TVIO_LOGGER=stdout
  - export TVIO_DEBUG=true
  - make test

after_success:
  - mkdir -p doc/html
  - git clone -b gh-pages https://github.com/ThingiverseIO/libthingiverseio.git --single-branch doc/html/
  - make doc
  - cd doc/html
  - git add .
  - git config user.name "Documentation Builder"
  - git config user.email "travis@thingiverse.io"
  - git commit -m "Automated documentation build for changeset $(git rev-parse --verify HEAD)."
  - git push origin gh-pages
